apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mysql
spec:
  storageClassName: ""  # <-- added to match the storage class of PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-http
spec:
  storageClassName: ""  # <-- added to match the storage class of PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
