apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: lesson16
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: web
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:                      # Здесь описано монтирование volume'а к контейнеру
            - name: secret-volume
              mountPath: "/usr/secrets/"
              readOnly: true
      volumes:                               # Здесь описан сам volume (том)
        - name: secret-volume
          secret:
            secretName: first-secret
