apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson14
  labels:
    app: goweb
spec:
  containers:
    - name: web
      image: nginx:latest ## укажите здесь свой образ из предыдущих уроков в формате 
                                 ## image: <имя_пользователя>/<репозиторий>/<тег>
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
