apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: lesson16
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"  # default используется по умолчанию, можно прописать тот класс,
  resources:                   # который сообщит Вам администратор
    requests:
      storage: 30Gi
