apiVersion: v1
kind: Service
metadata: 
  name: nodeport-goapp-service
  namespace: lesson14
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: goweb
