apiVersion: v1
kind: Service
metadata:
  name: my-balancer
  namespace: lesson14
spec:
  ports:
  - port: 8080
    name: webport
    targetPort: 80
  selector:
    app: goweb
  type: LoadBalancer
  # loadBalancerIP: 95.216.150.107
